/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PersonajeControlador;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Personaje;
import modelo.PersonajeDAO;

/**
 *
 * @author Kinidread
 */
public class BuscarPersonaje extends javax.swing.JInternalFrame {

    private final PersonajeControlador controlador;
    private final DefaultListModel<String> listaModelo;
    /**
     * Creates new form BuscarPersonaje
     */
    public BuscarPersonaje() {
        controlador = new PersonajeControlador(); // Inicializar el controlador
        listaModelo = new DefaultListModel<>();   // Inicializar el modelo de lista
        initComponents();
        
        // 2.1 Configuración manual de componentes después de initComponents()
        listBuscarPersonajes.setModel(listaModelo); // Asignar el modelo a la JList
        inicializarComponentes();
        cargarTodosLosPersonajesInicialmente();
    }
    
    private void inicializarComponentes() {
        // Añadir "TODOS" al ComboBox para permitir búsquedas sin filtro de tipo
        cbTipoPersonaje.addItem("TODOS"); 
        
        // El DefaultComboBoxModel de tu initComponents ya tiene los tipos de personajes.
        // Solo reordenamos para que "TODOS" sea el primero.
        String[] items = {"TODOS", "Guerrero", "Mago", "Arquero", "Sacerdote", "Asesino"};
        cbTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(items));
        cbTipoPersonaje.setSelectedItem("TODOS"); // Seleccionar 'TODOS' por defecto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listBuscarPersonajes = new javax.swing.JList<>();
        txtBuscarId = new javax.swing.JTextField();
        lBuscarPorId = new javax.swing.JLabel();
        lBuscarPorTipo = new javax.swing.JLabel();
        lBuscarPorNombre = new javax.swing.JLabel();
        txtBuscarNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbTipoPersonaje = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listBuscarPersonajes);

        lBuscarPorId.setText("Buscar por ID: ");

        lBuscarPorTipo.setText("Buscar por TIPO: ");

        lBuscarPorNombre.setText("Buscar por NOMBRE:");

        btnBuscar.setText("BUSCAR!");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerrero", "Mago", "Arquero", "Sacerdote", "Asesino" }));
        cbTipoPersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoPersonajeItemStateChanged(evt);
            }
        });
        cbTipoPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPersonajeActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lBuscarPorId)
                            .addComponent(lBuscarPorTipo)
                            .addComponent(lBuscarPorNombre))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarId)
                            .addComponent(txtBuscarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(cbTipoPersonaje, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscarPorId)
                    .addComponent(txtBuscarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscarPorTipo)
                    .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBuscarPorNombre)
                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoPersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoPersonajeItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            
        }
    }//GEN-LAST:event_cbTipoPersonajeItemStateChanged

    private void cbTipoPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPersonajeActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void mostrarResultados(List<Personaje> lista) {
        
        // 1. Añadir encabezado
        listaModelo.addElement(String.format("========================================================================================="));
        listaModelo.addElement(String.format("%-5s | %-15s | %-10s | %-8s | %-8s | %-8s | %-8s", 
                "ID", "NOMBRE", "CLASE", "SALUD", "MANA", "ATAQUE", "DEFENSA"));
        listaModelo.addElement(String.format("========================================================================================="));

        // 2. Añadir cada personaje
        for (Personaje p : lista) {
            String linea = String.format("%-5d | %-15s | %-10s | %-8d | %-8d | %-8d | %-8d",
                    p.getId(), p.getNombre(), p.getTipo(), p.getSalud(), p.getMana(), p.getAtaque(), p.getDefensa());
            listaModelo.addElement(linea);
        }
    }
    
    private void cargarTodosLosPersonajesInicialmente() {
        try {
            // Llamamos al controlador con parámetros vacíos. 
            // Como el campo ID y Nombre están vacíos, y el Tipo está en "TODOS", 
            // el DAO devolverá todos los registros.
            List<Personaje> resultados = controlador.buscarPersonajes("", "TODOS", "");

            if (resultados.isEmpty()) {
                listaModelo.addElement("Base de datos cargada. No hay personajes registrados.");
            } else {
                mostrarResultados(resultados);
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar la lista inicial: " + e.getMessage(), "Error de Conexión/BD", JOptionPane.ERROR_MESSAGE);
            listaModelo.addElement("ERROR: Fallo al conectar o cargar datos.");
        }
    }
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        // A. Obtener los filtros
        String id = txtBuscarId.getText().trim();
        String tipo = cbTipoPersonaje.getSelectedItem().toString(); // Ya añadimos "TODOS"
        String nombre = txtBuscarNombre.getText().trim();
        
        // Limpiar resultados anteriores
        listaModelo.clear(); 
        
        try {
            // B. Llamar al controlador para ejecutar la búsqueda
            List<Personaje> resultados = controlador.buscarPersonajes(id, tipo, nombre);

            // C. Mostrar los resultados
            if (resultados.isEmpty()) {
                listaModelo.addElement("⚠️ Búsqueda completada. No se encontraron personajes.");
            } else {
                mostrarResultados(resultados);
            }

        } catch (NumberFormatException e) {
            // Error si el ID introducido no es un número
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            listaModelo.addElement("Error: ID inválido.");
        } catch (Exception e) {
            // Error general (por ejemplo, de conexión a la BD)
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al ejecutar la búsqueda: " + e.getMessage(), "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
            listaModelo.addElement("Error: Fallo en la conexión o la consulta.");
        }
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String idTexto = txtBuscarNombre.getText().trim();
        
        if (!idTexto.isEmpty()) {
            int id = Integer.parseInt(idTexto);
            PersonajeDAO dao = new PersonajeDAO();
            
            if(dao.eliminarPersonajePorID(id)) {
                JOptionPane.showMessageDialog(this, "Personaje Eliminado");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el personaje.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nombreTexto = txtBuscarNombre.getText().trim();
        
        if (!nombreTexto.isEmpty()) {
            String nombre = nombreTexto;
            PersonajeDAO dao = new PersonajeDAO();
            
            if(dao.eliminarPersonajePorNombre(nombre)) {
                JOptionPane.showMessageDialog(this, "Personaje Eliminado");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar el personaje.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String tipoTexto = cbTipoPersonaje.getSelectedItem().toString();
        
        if (!tipoTexto.isEmpty()) {
            String tipo = tipoTexto;
            PersonajeDAO dao = new PersonajeDAO();
            
            if(tipo.equalsIgnoreCase("TODOS")){
                int r = JOptionPane.showConfirmDialog(
                        this,
                        "¿Seguro que quieres eliminar a todos los personajes?", 
                        "Confirmación",
                        JOptionPane.YES_NO_OPTION);
                if (r==JOptionPane.YES_OPTION) {
                    try {
                        dao.eliminarTodoPersonajes();
                        JOptionPane.showMessageDialog(this, "Todos los personajes fueron eliminados.");
                    } catch (SQLException ex) {
                        Logger.getLogger(BuscarPersonaje.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                return;
                
            }
            
            if(dao.eliminarPersonajePorTipo(tipo)) {
                JOptionPane.showMessageDialog(this, "Personajes Eliminado");
            }else{
                JOptionPane.showMessageDialog(this, "No se pudo eliminar los personajes.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbTipoPersonaje;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lBuscarPorId;
    private javax.swing.JLabel lBuscarPorNombre;
    private javax.swing.JLabel lBuscarPorTipo;
    private javax.swing.JList<String> listBuscarPersonajes;
    private javax.swing.JTextField txtBuscarId;
    private javax.swing.JTextField txtBuscarNombre;
    // End of variables declaration//GEN-END:variables
}
