/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.PersonajeControlador;

/**
 *
 * @author Kinidread
 */
public class CrearPersonaje extends javax.swing.JInternalFrame {

    private final PersonajeControlador controlador = new PersonajeControlador();
    /**
     * Creates new form CrearPersonaje
     */
    public CrearPersonaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblTipoPersonaje = new javax.swing.JLabel();
        lblCaracteristicas = new javax.swing.JLabel();
        btnIngresarPersonaje = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbTipoPersonaje = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCaracteristicas = new javax.swing.JList<>();
        lblImagenPersonaje = new javax.swing.JLabel();

        lblNombre.setText("Nombre: ");

        lblTipoPersonaje.setText("Tipo de Personaje: ");

        lblCaracteristicas.setText("Caracteristicas: ");

        btnIngresarPersonaje.setText("Ingresar Personaje!");
        btnIngresarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPersonajeActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar!");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbTipoPersonaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerrero", "Mago", "Arquero", "Sacerdote", "Asesino" }));
        cbTipoPersonaje.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTipoPersonajeItemStateChanged(evt);
            }
        });
        cbTipoPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoPersonajeActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listCaracteristicas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCaracteristicas)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoPersonaje)
                                    .addComponent(lblNombre))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombre)
                                    .addComponent(cbTipoPersonaje, 0, 140, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(lblImagenPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(btnIngresarPersonaje)
                        .addGap(98, 98, 98)
                        .addComponent(btnCancelar)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTipoPersonaje)
                            .addComponent(cbTipoPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(lblCaracteristicas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagenPersonaje, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarPersonaje)
                    .addComponent(btnCancelar))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbTipoPersonajeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoPersonajeItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        mostrarImagenSeleccionada();
        }
    }//GEN-LAST:event_cbTipoPersonajeItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:        
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnIngresarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPersonajeActionPerformed
        // TODO add your handling code here:
        String nombre = txtNombre.getText().trim();
    String tipo = (String) cbTipoPersonaje.getSelectedItem(); 

    if (nombre.isEmpty() || tipo == null || tipo.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Debe completar el nombre y seleccionar el tipo.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Llamar al Controlador y obtener el resultado
    if (controlador.guardarPersonaje(nombre, tipo)) {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Personaje " + nombre + " creado con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        this.dispose(); // Cierra la ventana
    } else {
        // El DAO ya muestra el error específico, pero podemos poner un mensaje general de fallo.
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el personaje. Revise los logs.", "Fallo", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnIngresarPersonajeActionPerformed

    private void cbTipoPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoPersonajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoPersonajeActionPerformed


    private void mostrarImagenSeleccionada(){
        String tipo = (String) cbTipoPersonaje.getSelectedItem();
        String rutaImagen = "";
        
        switch (tipo.toLowerCase()) {
        case "mago":
            rutaImagen = "/images/mago.png";
            break;
        case "asesino":
            rutaImagen = "/images/asesino.png";
            
            break;
        case "guerrero":
            rutaImagen = "/images/guerrero.png";
            break;
        case "sacerdote":
            rutaImagen = "/images/sacerdote.png";
            break;
        case "arquero":
            rutaImagen = "/images/arquero.png";
            break;
        default:
            rutaImagen = "/images/default.png";
            break;
        }
        try {
        // Usa ClassLoader para cargar el recurso de la imagen
        java.net.URL url = getClass().getResource(rutaImagen);
        
        if (url != null) {
            javax.swing.ImageIcon icono = new javax.swing.ImageIcon(url);
            
            // OPCIONAL: Escalar la imagen para que encaje en el JLabel
            java.awt.Image imagen = icono.getImage();
            java.awt.Image imagenEscalada = imagen.getScaledInstance(
                lblImagenPersonaje.getWidth(), 
                lblImagenPersonaje.getHeight(), 
                java.awt.Image.SCALE_SMOOTH
            );
            
            lblImagenPersonaje.setIcon(new javax.swing.ImageIcon(imagenEscalada));
        } else {
            lblImagenPersonaje.setIcon(null); // Borra la imagen si la ruta es incorrecta
            System.err.println("Imagen no encontrada: " + rutaImagen);
        }

        } catch (Exception e) {
            e.printStackTrace();
            lblImagenPersonaje.setIcon(null);
            }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresarPersonaje;
    private javax.swing.JComboBox<String> cbTipoPersonaje;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaracteristicas;
    private javax.swing.JLabel lblImagenPersonaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipoPersonaje;
    private javax.swing.JList<String> listCaracteristicas;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
